FROM python:3.9-slim

# Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

RUN apt-get update && apt-get install -y gcc
# Install production dependencies.
RUN pip install -r requirements/dev.txt

EXPOSE 8080

CMD python app/app.py